---
## YAML based inventory, see:
## https://docs.ansible.com/ansible/latest/plugins/inventory/yaml.html
#
## Simple example using defaults to spin up 3 RHEL 8.1 guests

kvmhost: # keys must be unique, i.e. only one 'hosts' per group
    hosts:
        kvmhost:
        localhost:
            var1: value1
    vars:
        group_var1: value2
    children:   # key order does not matter, indentation does
        other_group:
            children:
                group_x:
                    hosts:
                        test5
            vars:
                g2_var2: value3
            hosts:
                test4:
                    ansible_host: 127.0.0.1
        last_group:
            hosts:
                test1 # same host as above, additional group membership
            vars:
                last_var: MYVALUE




rhel81:
  hosts:
    simple-rhel-8.1-[0:2]:
      ansible_python_interpreter: /usr/bin/python
  vars:
